repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-yaml
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.45.0
    hooks:
    -   id: golangci-lint
