{
 "title": "Cost Analysis by Pod",
 "description": "Provides an analysis of costs by pod",
 "tags": [
  "mintel",
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(app_mintel_com_data_source)"
   },
   { "name": "costcpu", "label": "CPU", "query": "17.76" },
   { "name": "costpcpu", "label": "PE CPU", "query": "5.34" },
   { "name": "costram", "label": "RAM", "query": "2.38" },
   { "name": "costpram", "label": "PE RAM", "query": "0.71" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.040" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.170" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod))"
   }
  ]
 },
 "panels": [
  {
   "title": "Container cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*\n  ($costcpu - ($costcpu / 100 * $costDiscount))) by(container)  or  count(\n  count(container_spec_cpu_shares{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"})\n  by(container)  ) by(container) -1)+(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",\n  container!=\"POD\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*$costpcpu) by(container)  or\n  count(    count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by(container)  ) by(container) -1)\n",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}\n  /1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container)\n  or  count(    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by(container)  )\n  by(container) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}\n  /1024/1024/1024*$costpram) by(container)  or  count(    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"})\n  by(container)  ) by(container) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    { "expr": "vector(0)\n", "legendFormat": "{{ namespace }}" },
    {
     "expr": "(sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000\n  *($costcpu - ($costcpu / 100 * $costDiscount))) by(container)  or  count(count(container_spec_cpu_shares{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"})\n  by(container)  ) by(container) -1)+(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}\n  /1000*$costpcpu) by(container)  or count(    count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by(container)  )\n  by(container) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}\n  /1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container)\n  or  count( count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"})\n  by(container)  ) by(container) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",\n  cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*$costpram) by(container)  or  count(\n  count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by(container)  ) by(container) -1)\n"
    },
    {
     "expr": "sum(count(count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by (container))\n  by (container) * on (container) sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))\n  by (container)) by (container) * 1000/sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by (container) * 100\n",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(count(count(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"})\n  by (container)) by (container) * on (container)\n  sum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))\n  by (container)) by (container)/sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by (container) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (container)\n",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_cpu_shares{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by (container) / 1000\n",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (container)\n",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\",app_mintel_com_data_source=\"$cluster\"}) by (container)\n",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this pod, as a sum of its containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}