{
 "title": "Mintel /  Cost Analysis by Cluster",
 "description": "Provides an analysis of costs by cluster",
 "tags": [
  "mintel",
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(app_mintel_com_data_source)"
   },
   { "name": "costcpu", "label": "CPU", "query": "17.76" },
   { "name": "costpcpu", "label": "PE CPU", "query": "5.34" },
   { "name": "costram", "label": "RAM", "query": "2.38" },
   { "name": "costpram", "label": "PE RAM", "query": "0.71" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.040" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.170" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   { "name": "unaccountedNodeStorage", "label": "NS", "query": "4000000000" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows indicative monthly costing for the cluster, based on current requests for CPU, RAM and Storage.\nCurrent Region Prices are for BELGIUM.\n"
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "description": "This gauge shows the current CPU use vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",service=\"kubelet\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) / sum (machine_cpu_cores{service=\"kubelet\",app_mintel_com_data_source=\"$cluster\"}) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "This panel shows current CPU reservation requests by applications, vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) / sum (kube_node_status_allocatable_cpu_cores{app_mintel_com_data_source=\"$cluster\"})) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((sum(kube_node_status_capacity_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node)\n  * on (node) group_left (label_cloud_google_com_gke_preemptible) kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"})\n  * $costpcpu) or ((sum(kube_node_status_capacity_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node)\n  * on (node) group_left (label_cloud_google_com_gke_preemptible) kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"})\n  * ($costcpu - ($costcpu / 100 * $costDiscount))))\n"
    }
   ]
  },
  {
   "title": "Storage Cost (Cluster and PVC)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace)\n  group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) / 1024 / 1024 / 1024 * $costStorageSSD\n  + (sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace)\n  group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) / 1024 / 1024 / 1024 or on() vector(0) )* $costStorageStandard\n  + sum(node_filesystem_size_bytes{mountpoint=\"/mnt/stateful_partition\",app_mintel_com_data_source=\"$cluster\"} + $unaccountedNodeStorage) / 1024 / 1024 / 1024 * $costStorageSSD\n"
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "singlestat",
   "description": "This gauge shows current RAM use by RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",service=\"kubelet\",app_mintel_com_data_source=\"$cluster\"}) / sum (machine_memory_bytes{service=\"kubelet\",app_mintel_com_data_source=\"$cluster\"}) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "singlestat",
   "description": "This panel shows current RAM reservation requests by applications, vs RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(kube_pod_container_resource_requests_memory_bytes{app_mintel_com_data_source=\"$cluster\"})\n    / sum(kube_node_status_allocatable_memory_bytes{app_mintel_com_data_source=\"$cluster\"})) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((\n       sum(kube_node_status_capacity_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node)\n        * on (node) group_left (label_cloud_google_com_gke_preemptible)\n       kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}\n     ) /1024/1024/1024 * $costpram)\n   or\n   ((\n       sum(kube_node_status_capacity_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node)\n        * on (node) group_left (label_cloud_google_com_gke_preemptible)\n       kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}\n     ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))))\n"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "# CPU\nsum(((sum(kube_node_status_capacity_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node) * on (node) group_left (label_cloud_google_com_gke_preemptible)\nkube_node_labels{label_cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}) * $costpcpu)\nor ((sum(kube_node_status_capacity_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node) * on (node) group_left (label_cloud_google_com_gke_preemptible)\nkube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}) * ($costcpu - ($costcpu / 100 * $costDiscount)))) +\n# Storage\nsum (\nsum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass)\n+ on (persistentvolumeclaim, namespace) group_right(storageclass)\nsum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace)\n) / 1024 / 1024 /1024 * $costStorageSSD +\n(sum (\nsum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass)\n+ on (persistentvolumeclaim, namespace) group_right(storageclass)\nsum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace)\n) or on() vector(0)) / 1024 / 1024 /1024 * $costStorageStandard +\nsum(node_filesystem_size_bytes{mountpoint=\"/mnt/stateful_partition\",app_mintel_com_data_source=\"$cluster\"} + $unaccountedNodeStorage) / 1024 / 1024 / 1024 * $costStorageSSD +\n# RAM\nsum(((\n    sum(kube_node_status_capacity_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node)\n     * on (node) group_left (label_cloud_google_com_gke_preemptible)\n    kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}) /1024/1024/1024 * $costpram\n)\nor\n((\n    sum(kube_node_status_capacity_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node)\n     * on (node) group_left (label_cloud_google_com_gke_preemptible)\n    kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}\n  ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))\n))\n"
    }
   ]
  },
  {
   "title": "Cluster Node Utilisation by CPU and RAM requests",
   "type": "table",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node) / sum(kube_node_status_allocatable_memory_bytes{app_mintel_com_data_source=\"$cluster\"}) by (node)) * 100\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node) / sum(kube_node_status_allocatable_cpu_cores{app_mintel_com_data_source=\"$cluster\"}) by (node)) * 100\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Namespace cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{app_mintel_com_data_source=\"$cluster\"} * ($costcpu - ($costcpu / 100 * $costDiscount))) by (namespace)\n  #+(sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*$costpcpu) by (namespace)\n  #or count(count(container_spec_cpu_shares{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*($costram- ($costram\n  / 100 * $costDiscount))) by (namespace)\n  #+(sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*$costpram)\n  #by (namespace) or count(count(container_spec_memory_limit_bytes{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace))\n  by (namespace) / 1024 / 1024 / 1024 * $costStorageStandard or count(count(container_spec_cpu_shares{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "# Add the CPU\n  sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{app_mintel_com_data_source=\"$cluster\"} * ($costcpu - ($costcpu / 100 * $costDiscount))) by (namespace)\n  #+ (sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*$costpcpu)\n  #by (namespace) or count(count(container_spec_cpu_shares{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1)\n  +\n  # Add the RAM\n  sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by (namespace)\n  #+ (sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*$costpram)\n  #by (namespace) or count(count(container_spec_memory_limit_bytes{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1)\n  +\n  # Add the storage\n  (sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageStandard\n  or count(count(container_spec_cpu_shares{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\",image!=\"\",service=\"kubelet\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))\n  /  ignoring(namespace) group_left() (sum (kube_node_status_allocatable_cpu_cores{app_mintel_com_data_source=\"$cluster\"})) ) * 100\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(count(count(container_memory_working_set_bytes{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (pod, namespace)) by (pod, namespace) *\n  on (pod, namespace) sum(avg_over_time(container_memory_working_set_bytes{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))\n  by (pod, namespace)) by (namespace) / sum(container_spec_memory_limit_bytes{namespace!=\"\",app_mintel_com_data_source=\"$cluster\"}) by (namespace) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on(persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on(persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageStandard\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}