{
 "title": "Mintel /  Cost Analysis by Namespace",
 "description": "Provides an analysis of costs by namespace",
 "tags": [
  "mintel",
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(app_mintel_com_data_source)"
   },
   { "name": "costcpu", "label": "CPU", "query": "17.76" },
   { "name": "costpcpu", "label": "PE CPU", "query": "5.34" },
   { "name": "costram", "label": "RAM", "query": "2.38" },
   { "name": "costpram", "label": "PE RAM", "query": "0.71" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.040" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.170" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(pod)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n\n+\n\n(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*$costpcpu) by(pod)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(pod)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*$costpram) by(pod)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n",
     "legendFormat": "{{ namespace }}"
    },
    { "expr": "vector(0)\n", "legendFormat": "{{ namespace }}" },
    {
     "expr": "(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(pod)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n\n+\n\n(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1000*$costpcpu) by(pod)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n\n# Now ram\n\n+\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible!=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(pod)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",cloud_google_com_gke_preemptible=\"true\",app_mintel_com_data_source=\"$cluster\"}/1024/1024/1024*$costpram) by(pod)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by(pod)\n  ) by(pod) -1\n)\n"
    },
    {
     "expr": "sum(\n   count(count(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (pod)) by (pod)\n   * on (pod)\n   sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n) by (pod) * 1000\n/\nsum(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (pod) * 100\n",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(\n   count(count(container_memory_working_set_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (pod)) by (pod)\n   * on (pod)\n   sum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (pod)\n) by (pod)\n/\nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (pod) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\",app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\",app_mintel_com_data_source=\"$cluster\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\",app_mintel_com_data_source=\"$cluster\"})\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageStandard\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Overall CPU Utilisation",
   "type": "graph",
   "description": "This panel shows historical utilisation as an average across all pods in this namespace.  It only accounts for currently deployed pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))\n  by (namespace) * 1000 / sum(avg_over_time(container_spec_cpu_shares{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (namespace) * 100\n",
     "legendFormat": "% cpu"
    }
   ]
  },
  {
   "title": "Overall RAM Utilisation",
   "type": "graph",
   "description": "This panel shows historical utilisation as an average across all pods in this namespace.  It only accounts for currently deployed pods",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (namespace) /\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}) by (namespace) * 100\n",
     "legendFormat": "% ram"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this namespace, as a sum of the pods within it",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (namespace)\n",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (namespace)\n",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk reads and writes for the namespace, as a sum of the pods within it",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (namespace)\n",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",app_mintel_com_data_source=\"$cluster\"}[$__interval])) by (namespace)\n",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}