{
 "title": "Mintel /  Event Bus",
 "description": "Provides an overview of the Mintel Event Bus",
 "tags": [
  "mintel",
  "event-bus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(aws_resource_info{job=\"aws_sns\", tag_MintelEventBus=\"true\"}, topic_name)"
   },
   {
    "name": "queue",
    "query": "label_values(aws_resource_info{job=\"aws_sqs\", tag_MintelEventBus=\"true\", tag_TopicName=~\"$topic\"}, queue_name)"
   },
   {
    "name": "event_type",
    "label": "Event Type",
    "query": "label_values({__name__=~\"event_bus_ebtailer_events_total|event_bus_ebtailer_invalid_events_total\", event_type=~\"com\\\\.mintel\\\\.topics\\\\.$topic\\\\.v\\\\d+\\\\..*\"}, event_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "EBTailer Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{namespace=\"mdp\", app_kubernetes_io_name=\"ebtailer\"})"
    }
   ]
  },
  {
   "title": "Message Problems",
   "type": "graph",
   "description": "This panel shows the rate of various kinds of problems with event bus messages:\n- `No Type Attribute`: The SQS message lacks a \"type\" attribute that says what message type it contains.\n- `Event Type Unknown to EBTailer - {{event_type}}` - The SQS message has a \"type\" attribute, but EBTailer wasn't compile with this Protobuf definition. EBTailer cannot validate the message contents.\n- `Deserialization Failed - {{event_type}}` - EBTailer was compiled with this Protobuf message type, but failed to deserialize the event message.\n\nNote: this panel isn't effected by the Topic/Event Type selectors at the top of the page.\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "msg / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_bus_ebtailer_messages_unknown_type_total[$__rate_interval]))",
     "legendFormat": "No Type Attribute"
    },
    {
     "expr": "sum(rate(event_bus_ebtailer_events_total{known_to_ebtailer=\"false\"}[$__rate_interval])) by (event_type)",
     "legendFormat": "Event Type Unknown to EBTailer - {{event_type}}"
    },
    {
     "expr": "sum(rate(event_bus_ebtailer_invalid_events_total[$__rate_interval])) by (event_type)",
     "legendFormat": "Deserialization Failed - {{event_type}}"
    }
   ]
  },
  {
   "title": "Event Rate by Topic",
   "type": "graph",
   "description": "This includes any message EBTailer received with a \"type\" attribute, even ones it didn't have the Protobuf definition to deserialize the message with.\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(event_bus_ebtailer_events_total{event_type=~\"$event_type\"}[$__rate_interval]), \"topic\", \"$1\", \"event_type\", \"com\\\\.mintel\\\\.topics\\\\.(.*)\\\\.v\\\\d+\\\\..*\")) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Event Rate by Event Type",
   "type": "graph",
   "description": "This includes any message EBTailer received with a \"type\" attribute, even ones it didn't have the Protobuf definition to deserialize the message with.\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_bus_ebtailer_events_total{event_type=~\"$event_type\"}[$__rate_interval])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}