{
 "title": "Hypervisor Libvirt Domain Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(libvirt_up, app_mintel_com_site)"
   },
   {
    "name": "hypervisor",
    "label": "Hypervisor",
    "query": "label_values(libvirt_up{app_mintel_com_site=~\"$site\"}, instance)"
   },
   {
    "name": "domain",
    "label": "VM",
    "query": "label_values(libvirt_domain_info_virtual_cpus{app_mintel_com_site=~\"$site\",instance=~\"$hypervisor\"}, domain)"
   }
  ]
 },
 "panels": [
  {
   "title": "VM CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{instance=~\"$hypervisor\", domain=~\"$domain\"}[5m]) / 1000000000 / on (instance) group_left instance:node_cpus:count{instance=~\"$hypervisor\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "VM Block Device I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (domain)(rate(libvirt_domain_block_stats_read_bytes_total{instance=~\"$hypervisor\", domain=~\"$domain\"}[5m]))",
     "legendFormat": "{{domain}} - Read"
    },
    {
     "expr": "sum by (domain)(rate(libvirt_domain_block_stats_write_bytes_total{instance=~\"$hypervisor\", domain=~\"$domain\"}[5m]))",
     "legendFormat": "{{domain}} - Write"
    }
   ]
  },
  {
   "title": "VM Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{instance=~\"$hypervisor\", domain=~\"$domain\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "VM Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (domain)(rate(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$hypervisor\", domain=~\"$domain\"}[5m]))",
     "legendFormat": "{{domain}} - Rx"
    },
    {
     "expr": "sum by (domain)(rate(libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$hypervisor\", domain=~\"$domain\"}[5m]))",
     "legendFormat": "{{domain}} - Tx"
    }
   ]
  }
 ]
}