{
 "title": "Node Exporter - Refined",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "component",
    "label": "Component",
    "query": "label_values(node_uname_info, app_mintel_com_job_label)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{app_mintel_com_job_label=~\"$component\"}, instance)"
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU ",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))) - avg(sum by (mode,instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(node_load5{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load15{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) - sum(node_memory_MemFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})) / sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} ) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_SwapFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} )) * 100)"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "gauge",
   "description": "Disk space used",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}) - sum by (mountpoint)(node_filesystem_avail_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})) / sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "bargauge",
   "description": "Status of physical network interfaces",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "{device}}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_carrier{device=~\"eth.*\", instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}",
     "legendFormat": "{{device}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Is Hypervisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{instance=~\"$node\"} * node_exporter_build_info{hypervisor=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "gauge",
   "description": "Allocated File Descriptors",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filefd_allocated{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) / sum(node_filefd_maximum{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "gauge",
   "description": "Inode Usage",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (mountpoint)(node_filesystem_files{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}) - sum by (mountpoint)(node_filesystem_files_free{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})) / sum by (mountpoint)(node_filesystem_files{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_time_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_boot_time_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "DataFS Total",
   "type": "singlestat",
   "description": "Total DataFS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",mountpoint=\"/data\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Sockets Used",
   "type": "stat",
   "description": "Number of sockets in use",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_sockets_used{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  { "title": "Quick CPU / Mem / Disk - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU ",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))) - avg(sum by (mode,instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(node_load5{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load15{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance)) * 100",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) - sum(node_memory_MemFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})) / sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} ) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_SwapFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} )) * 100)"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "gauge",
   "description": "Disk space used",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}) - sum by (mountpoint)(node_filesystem_avail_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})) / sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "bargauge",
   "description": "Status of physical network interfaces",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "{device}}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_carrier{device=~\"eth.*\", instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}",
     "legendFormat": "{{device}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Is Hypervisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{instance=~\"$node\"} * node_exporter_build_info{hypervisor=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) by (cpu,instance))"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "gauge",
   "description": "Allocated File Descriptors",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filefd_allocated{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}) / sum(node_filefd_maximum{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "gauge",
   "description": "Inode Usage",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (mountpoint)(node_filesystem_files{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}) - sum by (mountpoint)(node_filesystem_files_free{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})) / sum by (mountpoint)(node_filesystem_files{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_time_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_boot_time_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "DataFS Total",
   "type": "singlestat",
   "description": "Total DataFS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",mountpoint=\"/data\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Sockets Used",
   "type": "stat",
   "description": "Number of sockets in use",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_sockets_used{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "avg(node_load1{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "avg(node_load5{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "avg(node_load15{instance=~\"$node\",job=~\"$job\"})",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"eth.*\"}[5m])*8)",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"eth.*\"}[5m])*8)",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_MemFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_Buffers_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_Cached_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_Slab_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_PageTables_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_SwapCached_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "sum(node_memory_PageTables_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "sum(node_memory_SwapCached_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "sum(node_memory_Slab_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "sum(node_memory_Cached_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "sum(node_memory_Buffers_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "sum(node_memory_MemFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"} - node_memory_SwapFree_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "sum(node_memory_HardwareCorrupted_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_reads_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"$diskdevices\"}[5m]))",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "sum by (device)(irate(node_disk_writes_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"$diskdevices\"}[5m]))",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "((sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}) - sum by (mountpoint)(node_filesystem_avail_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})) / sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s", "label": "time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_read_time_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) / sum by (device)(irate(node_disk_reads_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Read time"
      },
      {
       "expr": "sum by (device)(irate(node_disk_write_time_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])) / sum by (device)(irate(node_disk_writes_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Write time"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_read_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"$diskdevices\"}[5m]))",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "sum by (device)(irate(node_disk_written_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"$diskdevices\"}[5m]))",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_Committed_AS_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "sum(node_memory_CommitLimit_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_Writeback_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "sum(node_memory_WritebackTmp_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "sum(node_memory_Dirty_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Pages In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_vmstat_pgpgin{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "sum(irate(node_vmstat_pgpgout{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_vmstat_pswpin{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "sum(irate(node_vmstat_pswpout{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short", "label": "faults" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_vmstat_pgfault{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "sum(irate(node_vmstat_pgmajfault{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "sum(irate(node_vmstat_pgfault{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m])  - irate(node_vmstat_pgmajfault{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Pgminfault - Minor page fault operations"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_vmstat_oom_kill{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "oom killer invocations "
      }
     ]
    }
   ]
  },
  {
   "title": "System Timesync - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Syncronized Drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "avg(node_timex_estimated_error_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "avg(node_timex_offset_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "avg(node_timex_maxerror_seconds{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Time Syncronized Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no) - {{instance}}"
      },
      {
       "expr": "avg(node_timex_frequency_adjustment_ratio{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    }
   ]
  },
  {
   "title": "System Processes - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_processes_state{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_processes_threads{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "forks / sec" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_forks_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Process schedule stats Running / Waiting",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum by (cpu)(irate(node_schedstat_running_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
      },
      {
       "expr": "sum by (cpu)(irate(node_schedstat_waiting_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "System Misc - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_context_switches_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Context switches"
      },
      {
       "expr": "sum(irate(node_intr_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "Individual Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (info) (irate(node_interrupts_total_sum{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{info}}"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "avg(node_entropy_available_bits{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "Schedule timeslices executed by each cpu",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum by (cpu)(irate(node_schedstat_timeslices_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "CPU time spent in user and system contexts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(irate(process_cpu_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "Time spent"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd / Init - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Systemd Sockets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum by (name)(irate(node_systemd_socket_accepted_connections_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{ name }} Connections"
      }
     ]
    },
    {
     "title": "Systemd Units / Init Services State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(node_systemd_units{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",state=\"activating\"})",
       "legendFormat": "Activating"
      },
      {
       "expr": "sum(node_systemd_units{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",state=\"active\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(node_systemd_units{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",state=\"deactivating\"})",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "sum(node_systemd_units{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",state=\"failed\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(node_systemd_units{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",state=\"inactive\"})",
       "legendFormat": "Inactive"
      },
      {
       "expr": "sum(node_system_service_status{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Running"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_reads_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "sum by (device)(irate(node_disk_writes_completed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_read_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "sum by (device)(irate(node_disk_written_bytes_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "time" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_io_time_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device=~\"$diskdevices\"} [5m]))",
       "legendFormat": "{{device}} - Time spent doing I/Os"
      }
     ]
    },
    {
     "title": "Disk Average Queue Depth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - IO time weighted"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_reads_merged_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "sum by (device)(irate(node_disk_writes_merged_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_disk_io_time_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - IO time"
      },
      {
       "expr": "sum by (device)(irate(node_disk_discard_time_seconds_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - discard time"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (mountpoint)(node_filesystem_avail_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}} - Available"
      },
      {
       "expr": "sum by (mountpoint)(node_filesystem_size_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}} - Size"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "file nodes" }
     ],
     "targets": [
      {
       "expr": "sum by (mountpoint)(node_filesystem_files_free{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "files" }
     ],
     "targets": [
      {
       "expr": "sum(node_filefd_maximum{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Max open files"
      },
      {
       "expr": "sum(node_filefd_allocated{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly / Error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum by (mountpoint)(node_filesystem_readonly{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      },
      {
       "expr": "sum by (mountpoint)(node_filesystem_device_error{instance=~\"$node\",app_mintel_com_job_label=~\"$component\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}} - Device error"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_packets_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum by (device)(irate(node_network_transmit_packets_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_errs_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "sum by (device)(irate(node_network_transmit_errs_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_drop_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "sum by (device)(irate(node_network_transmit_drop_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_compressed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "sum by (device)(irate(node_network_transmit_compressed_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_multicast_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum by (device)(irate(node_network_receive_fifo_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "sum by (device)(irate(node_network_transmit_fifo_total{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "avg by (device)(node_arp_entries{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_alloc{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "sum(node_sockstat_TCP_inuse{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=\"$node\",app_mintel_com_job_label=~\"$component\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$node\",app_mintel_com_job_label=~\"$component\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(node_sockstat_UDPLITE_inuse{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "sum(node_sockstat_UDP_inuse{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "sum(node_sockstat_UDP_mem{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "sum(node_sockstat_sockets_used{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_mem_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "mem_bytes - TCP sockets in that state"
      },
      {
       "expr": "sum(node_sockstat_UDP_mem_bytes{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"})",
       "legendFormat": "mem_bytes - UDP sockets in that state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Icmp_InMsgs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Icmp_OutMsgs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Icmp_InErrors{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InDatagrams{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "datagrams" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InErrors{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_NoPorts{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
      },
      {
       "expr": "sum(irate(node_netstat_UdpLite_InErrors{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "RcvbufErrors - UDP buffer errors received"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "SndbufErrors - UDP buffer errors send"
      }
     ]
    },
    {
     "title": "TCP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Tcp_InSegs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_OutSegs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "sum(irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "sum(irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_InErrs{instance=~\"$node\",app_mintel_com_job_label=~\"$component\"}[5m]))",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      }
     ]
    }
   ]
  }
 ]
}