{
 "title": "On-prem Windows RDP Environments",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(wmi_cs_hostname, app_mintel_com_job_label)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(wmi_cs_hostname{app_mintel_com_job_label=\"$env\"}, instance)"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "label_values(wmi_process_cpu_time_total{instance=~\"$instance\"},process)"
   }
  ]
 },
 "panels": [
  {
   "title": "Remote Interactive Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_logon_logon_type{status=\"network\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "App Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (process, instance) (wmi_process_cpu_time_total{process=~\"$process\",instance=~\"$instance\",mode=\"user\"})",
     "legendFormat": "{{process}} - {{instance}}"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Load - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode!~\"(idle|dpc|interrupt)\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode!~\"(idle|dpc|interrupt)\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode!~\"(idle|dpc|interrupt)\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$instance\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$instance\"} - wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "In Use Physical Memory"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    }
   ]
  },
  {
   "title": "Memory - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$instance\"} - wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "In Use Physical Memory"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    }
   ]
  },
  {
   "title": "Memory - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$instance\"} - wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "In Use Physical Memory"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "repeat": "instance",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_sent_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_sent_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_sent_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_total{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Discarded/Error Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_outbound_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Discarded/Error Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_outbound_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Discarded/Error Packets - $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_outbound_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(wmi_net_packets_received_discarded{instance=~\"$instance\", nic!~ \"isatap.+\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Hard Drive iOps - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "repeat": "instance",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_split_ios_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive iOps - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_split_ios_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive iOps - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_split_ios_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Free Space - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Free Space - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Free Space - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Throughput - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "repeat": "instance",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Throughput - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Throughput - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Disk Queue Length - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_requests_queued{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Disk Queue Length - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_requests_queued{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Hard Drive Disk Queue Length - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_requests_queued{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_threads{instance=~\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_threads{instance=~\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_threads{instance=~\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Exception Dispatches - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "repeat": "instance",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_system_exception_dispatches_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Exception Dispatches - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_system_exception_dispatches_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Exception Dispatches - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_system_exception_dispatches_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Services by State - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (wmi_service_state{instance=~\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Services by State - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (wmi_service_state{instance=~\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Services by State - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (wmi_service_state{instance=~\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "WMI Exporter Performance - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_exporter_collector_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "WMI Exporter Performance - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_exporter_collector_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "WMI Exporter Performance - $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_exporter_collector_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}