{
 "title": "On-prem Prometheus Summary",
 "time": { "from": "now-7d", "to": "now-2m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(prometheus_build_info, app_mintel_com_data_source)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(prometheus_build_info{app_mintel_com_data_source=~\"$site\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total{mode=~\"(system|user|iowait|irq|softirq)\",app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[5m])) * 100) / (count(node_cpu_guest_seconds_total{app_mintel_com_job_label=~\".*prometheus.*\",mode=\"user\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} - node_memory_MemFree_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} - (node_memory_Cached_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} + node_memory_Buffers_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))) / (sum(node_memory_MemTotal_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Shard Fulfillment",
   "type": "gauge",
   "description": "Desired shards / active shards",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((sum by (url)(prometheus_remote_storage_shards_desired{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}) / sum by (url)(prometheus_remote_storage_shards{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"})), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
     "legendFormat": "{{cortex}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (app_mintel_com_data_source)(sum by(app_mintel_com_data_source, instance)(prometheus_target_scrape_pool_targets{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\",scrape_job=\"node_exporter\"})))",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(max by (app_mintel_com_data_source)(sum by(app_mintel_com_data_source, instance)(prometheus_target_scrape_pool_targets{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\",scrape_job=\"snmp_sys_uptime\"})))",
     "legendFormat": "SNMP"
    },
    {
     "expr": "sum(max by (app_mintel_com_data_source)(sum by(app_mintel_com_data_source, instance)(prometheus_target_scrape_pool_targets{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\",scrape_job=\"windows_exporter\"})))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (app_mintel_com_data_source)(sum by(app_mintel_com_data_source, instance)(prometheus_target_scrape_pool_targets{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"})))"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(prometheus_remote_storage_samples_in_total{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")"
    }
   ]
  },
  {
   "title": "Prometheus Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\",app_mintel_com_job_label=\"infra/prometheus\",system_unit=\"prometheus.service\"} != \"level=info\""
    }
   ]
  },
  {
   "title": "Throughput to Cortex (Mbps)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((irate(node_network_transmit_bytes_total{app_mintel_com_job_label=~\".*prometheus.*\",device=~\"eth.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[5m])*8/1024/1024))"
    }
   ]
  },
  {
   "title": "Failing Scrapes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{app_mintel_com_data_source=~\"$site\"} < 1)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance)(irate(node_cpu_seconds_total{mode=~\"(system|user|iowait|irq|softirq)\",app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[5m])) * 100) / (count by (instance)(node_cpu_guest_seconds_total{app_mintel_com_job_label=~\".*prometheus.*\",mode=\"user\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Memory (%) ex buffers/cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance)(node_memory_MemTotal_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} - node_memory_MemFree_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} - (node_memory_Cached_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"} + node_memory_Buffers_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))) / (sum by (instance)(node_memory_MemTotal_bytes{app_mintel_com_job_label=~\".*prometheus.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_network_receive_bytes_total{app_mintel_com_job_label=~\".*prometheus.*\",device=~\"eth.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[5m])*8)",
       "legendFormat": "{{instance}} - In"
      },
      {
       "expr": "-sum by (instance)(irate(node_network_transmit_bytes_total{app_mintel_com_job_label=~\".*prometheus.*\",device=~\"eth.*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[5m])*8)",
       "legendFormat": "{{instance}} - Out"
      }
     ]
    },
    {
     "title": "Disk Usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{app_mintel_com_job_label=~\".*prometheus.*\", mountpoint=\"/data\", instance!~\"(dev|test).*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}-node_filesystem_avail_bytes{app_mintel_com_job_label=~\".*prometheus.*\", mountpoint=\"/data\", instance!~\"(dev|test).*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"})/node_filesystem_size_bytes{app_mintel_com_job_label=~\".*prometheus.*\", mountpoint=\"/data\", instance!~\"(dev|test).*\",app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Remote storage shards - Actual",
   "type": "graph",
   "description": "Current number of active shards",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "label_replace(sum by (instance, url)(prometheus_remote_storage_shards{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
     "legendFormat": "{{instance}} - {{cortex}}"
    }
   ]
  },
  {
   "title": "Remote storage shards - Desired",
   "type": "graph",
   "description": "Current number of desired shards",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "label_replace(sum by (instance, url)(prometheus_remote_storage_shards_desired{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
     "legendFormat": "{{instance}} - {{cortex}}"
    }
   ]
  },
  {
   "title": "Samples sent to remote storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Samples",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "counterResetValue": "1",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "expr": "sum by (instance)(rate(prometheus_remote_storage_samples_in_total{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Samples Sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by (instance,url)(rate(prometheus_remote_storage_samples_total{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
       "legendFormat": "{{instance}} - {{cortex}}"
      }
     ]
    },
    {
     "title": "Failed Samples",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by (instance,url)(rate(prometheus_remote_storage_samples_failed_total{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
       "legendFormat": "{{instance}} - {{cortex}}"
      }
     ]
    },
    {
     "title": "Pending Samples",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by (instance,url)(rate(prometheus_remote_storage_samples_pending{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
       "legendFormat": "{{instance}} - {{cortex}}"
      }
     ]
    }
   ]
  },
  { "title": "Queue & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Latency (time to send batch)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "aggregator": "p95",
     "alias": "95th Percentile",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])) by (le) ",
     "legendFormat": "{{le}}",
     "target": "Bosun Query"
    }
   ]
  },
  {
   "title": "Sent Batch Duration (90th percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (instance,url)(histogram_quantile(0.9, prometheus_remote_storage_sent_batch_duration_seconds_bucket{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"})), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
     "legendFormat": "{{instance}} - {{cortex}}"
    }
   ]
  },
  {
   "title": "Total Retries to Enqueue",
   "type": "graph",
   "description": "Total attempts to enqueue information in a remote storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "label_replace(sum by (instance,url)(rate(prometheus_remote_storage_enqueue_retries_total{app_mintel_com_data_source=~\"$site\",instance=~\"$instance\"}[1m])), \"cortex\", \"$1\", \"url\", \"https://(.*).cortex.*\")",
     "legendFormat": "{{instance}} - {{cortex}}"
    }
   ]
  }
 ]
}