{
 "title": "On-prem Blackbox",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(probe_success, target_alias)"
   },
   {
    "name": "probe",
    "label": "Probe",
    "query": "label_values(probe_success, probe_region)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "repeat": "target",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) /  count by (target_alias) (probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{target_alias}}"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "target" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 104 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 113 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 122 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 131 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 131 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 131 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 140 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 149 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 149 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 149 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 156 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} == 1) / count(probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 156 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_http_ssl{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target_alias=~\"$target\",probe_region=~\"$probe\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 156 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(probe_http_status_code{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "Avg Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 158 },
   "repeat": "probe",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 158 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 158 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{target_alias=~\"$target\",probe_region=~\"$probe\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "(1 - probe_success{target_alias=~\"$target\",probe_region=~\"$probe\"} > 0)",
     "legendFormat": "Down"
    }
   ]
  }
 ]
}