{
 "title": "Logstash metrics",
 "description": "Logstash monitoring via prometheus",
 "tags": [
  "prometheus",
  "elasticsearch",
  "logstash"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "component",
    "label": "Component",
    "query": "label_values(logstash_info_jvm, app_mintel_com_job_label)"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(logstash_info_jvm{app_mintel_com_job_label=~\"$component\"}, app_mintel_com_site)"
   }
  ]
 },
 "panels": [
  { "title": "PIPELINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_duration_seconds_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events in rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_in_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events filtered rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_filtered_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events out rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_out_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "PLUGINS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_duration_seconds_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])) by (plugin,plugin_id)",
     "legendFormat": "{{plugin}} - {{plugin_id}}"
    }
   ]
  },
  {
   "title": "Failures rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_failures_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events In rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_in_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events Out rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_mem_heap_used_bytes{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}",
     "legendFormat": "{{instance}} - heap used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_process_open_filedescriptors{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_duration_seconds_total{app_mintel_com_site=~\"$site\",app_mintel_com_job_label=~\"$component\"}[5m])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  }
 ]
}