{
 "title": "ISP Throughput",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Shanghai",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"core2-vlan2.shanghai.mintel.ad\",ifName=\"B1\"}[5m])) * 8",
     "legendFormat": "China Telecom - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"core2-vlan2.shanghai.mintel.ad\",ifName=\"B1\"}[5m])) * 8",
     "legendFormat": "China Telecom - In"
    }
   ]
  },
  {
   "title": "Shanghai",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"core3-vlan2.shanghai.mintel.ad\",ifName=\"B2\"}[5m])) * 8",
     "legendFormat": "Zayo - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"core3-vlan2.shanghai.mintel.ad\",ifName=\"B2\"}[5m])) * 8",
     "legendFormat": "Zayo - In"
    }
   ]
  },
  {
   "title": "Chi-DC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum (rate(ifOutOctets{instance=~\"chi-dc-edge0.*.chi-dc.mintel.ad\",ifName=\"eth0\"}[5m])) * 8",
     "legendFormat": "GTT - Out"
    },
    {
     "expr": "sum (rate(ifInOctets{instance=~\"chi-dc-edge0.*.chi-dc.mintel.ad\",ifName=\"eth0\"}[5m])) * 8",
     "legendFormat": "GTT - In"
    }
   ]
  },
  {
   "title": "Lon-DC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"vlan4-lon-ef-core2.lon-dc.mintel.ad\",ifName=\"1/48\"}[5m])) * 8",
     "legendFormat": "Exponential-E - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"vlan4-lon-ef-core2.lon-dc.mintel.ad\",ifName=\"1/48\"}[5m])) * 8",
     "legendFormat": "Exponential-E - In"
    }
   ]
  },
  {
   "title": "Chicago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"vlan40.core4.chicago.mintel.ad\",ifName=\"B24\"}[5m])) * 8",
     "legendFormat": "Zayo - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"vlan40.core4.chicago.mintel.ad\",ifName=\"B24\"}[5m])) * 8",
     "legendFormat": "Zayo - In"
    }
   ]
  },
  {
   "title": "Chicago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"vlan40.core3.chicago.mintel.ad\",ifName=\"B23\"}[5m])) * 8",
     "legendFormat": "Cogent - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"vlan40.core3.chicago.mintel.ad\",ifName=\"B23\"}[5m])) * 8",
     "legendFormat": "Cogent - In"
    }
   ]
  },
  {
   "title": "Singapore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"sg-off-core1.apac.mintel.ad\",ifName=\"A1\"}[5m])) * 8",
     "legendFormat": "StarHub / NGN SWE - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"sg-off-core1.apac.mintel.ad\",ifName=\"A1\"}[5m])) * 8",
     "legendFormat": "StarHub / NGN SWE - In"
    }
   ]
  },
  {
   "title": "Singapore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"sg-off-core2.apac.mintel.ad\",ifName=\"A1\"}[5m])) * 8",
     "legendFormat": "Citic Telecom (Pacific) - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"sg-off-core2.apac.mintel.ad\",ifName=\"A1\"}[5m])) * 8",
     "legendFormat": "Citic Telecom (Pacific) - In"
    }
   ]
  },
  {
   "title": "Kuala Lumpur",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"sunway.apac.mintel.ad\", ifName=\"Gi0.101\"}[5m])) * 8",
     "legendFormat": "Time - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"sunway.apac.mintel.ad\", ifName=\"Gi0.101\"}[5m])) * 8",
     "legendFormat": "Time - In"
    }
   ]
  },
  {
   "title": "Kuala Lumpur",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"sunway.apac.mintel.ad\", ifName=\"Gi0.500\"}[5m])) * 8",
     "legendFormat": "UniFi - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"sunway.apac.mintel.ad\", ifName=\"Gi0.500\"}[5m])) * 8",
     "legendFormat": "UniFi - In"
    }
   ]
  },
  {
   "title": "London - Mintel House",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"lon-mh-core5.london.mintel.ad\",ifName=\"A3\"}[5m])) * 8",
     "legendFormat": "Exponential-E - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"lon-mh-core5.london.mintel.ad\",ifName=\"A3\"}[5m])) * 8",
     "legendFormat": "Exponential-E - In"
    }
   ]
  },
  {
   "title": "London - Mintel House",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(ifOutOctets{instance=\"lon-mh-core6.london.mintel.ad\",ifName=\"A6\"}[5m])) * 8",
     "legendFormat": "Cogent - Out"
    },
    {
     "expr": "sum(rate(ifInOctets{instance=\"lon-mh-core6.london.mintel.ad\",ifName=\"A6\"}[5m])) * 8",
     "legendFormat": "Cogent - In"
    }
   ]
  }
 ]
}