{
 "title": "Radius TLS Handshakes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TLS handshakes across all RADIUS servers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (protocol) (count_over_time({job=\"winlog\",channel=\"System\"} |= \"Schannel\" != \"Error\" |= \"Protocol\" [1m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "TLS 1.2 handshakes per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({job=\"winlog\",channel=\"System\",protocol=\"TLS 1.2\"} |= \"Schannel\" [1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TLS 1.1 handshakes per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({job=\"winlog\",channel=\"System\",protocol=\"TLS 1.1\"} |= \"Schannel\" [1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TLS 1.0 handshakes per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({job=\"winlog\",channel=\"System\",protocol=\"TLS 1.0\"} |= \"Schannel\" [1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}