{
 "title": "API Gateway HAProxy",
 "description": "HAProxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(haproxy_server_status, instance)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_status{instance=~\"$node\"}, proxy)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_status{instance=~\"$node\"}, proxy)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_status{instance=~\"$node\"}, server)"
   }
  ]
 },
 "panels": [
  { "title": "Status - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=~\"$node\"} == 1)",
     "legendFormat": "Frontends Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=~\"$node\"} ==1)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  { "title": "Status - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=~\"$node\"} == 1)",
     "legendFormat": "Frontends Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=~\"$node\"} ==1)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total number of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{proxy=~\"$backend\",instance=~\"$node\"}[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m])*8)",
     "legendFormat": "IN Frontend"
    },
    {
     "expr": "sum(irate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m])*8)",
     "legendFormat": "OUT Frontend"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=~\"$node\"}[5m])*8)",
     "legendFormat": "IN Backend"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$node\"}[5m])*8)",
     "legendFormat": "OUT Backend"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend errors"
    }
   ]
  },
  {
   "title": "Total received requests / responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Frontend requests"
    },
    {
     "expr": "sum(irate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Frontend requests errors"
    },
    {
     "expr": "sum(irate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Frontend request denied"
    },
    {
     "expr": "sum(irate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend redispatch warnings"
    },
    {
     "expr": "sum(irate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend retry warnings"
    },
    {
     "expr": "sum(irate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend response errors"
    },
    {
     "expr": "sum(irate(haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend queued requests"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend requests"
    }
   ]
  },
  {
   "title": "Number of active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Frontend current sessions"
    },
    {
     "expr": "sum(irate(haproxy_backend_current_sessions{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Backend current sessions"
    }
   ]
  },
  {
   "title": "Throughtput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Maximum observed number of connections per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total number of connections reuses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend - Current number of queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Avg. queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_http_queue_time_average_seconds{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Total HTTP requests OK / Error / Denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Total HTTP responses Denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total HTTP requests OK / Denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_requests_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_requests_denied_total{proxy=~\"$frontend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total of Redispatch / Error / Retry warnings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Avg. Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_http_connect_time_average_seconds{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Avg. connect time  {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_backend_http_response_time_average_seconds{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Avg. response time  {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_backend_http_total_time_average_seconds{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Avg. total time  {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, code) (irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Backend - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_responses_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Denied by \"tcp-request session\" rules {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_frontend_current_sessions{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_backend_current_sessions{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_max_sessions{proxy=~\"$backend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Maximum observed number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_frontend_max_session_rate{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Maximum observed number of sessions per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_max_session_rate{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Frontend - Total HTTP Sessions Denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_client_aborts_total{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "sum by (proxy) (haproxy_backend_server_aborts_total{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend - Total number of UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total weight of the servers in the backend / Active servers backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_weight{proxy=~\"$backend\", instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_last_session_seconds{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Total number of times a service was selected",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_loadbalanced_total{proxy=~\"$backend\", instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Backend - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Frontend - Compressor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Backend - Compressor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Frontend - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_frontend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Backend - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (irate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_frontend_status{proxy=~\"$frontend\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend - Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_status{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Throughtput / Connections / Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (proxy, server) (haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of queued requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Avg. queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_http_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of Retry / Error / Redispatch warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Backend - Average times",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_http_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "Avg. connect time  {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (haproxy_server_http_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "Avg. response time  {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (haproxy_server_http_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "Avg. total time  {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server, code) (irate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} {{ server }} {{ code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (haproxy_server_limit_sessions{proxy=~\"$backend\",instance=~\"$node\"})",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_client_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (haproxy_server_server_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Health / Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total downtime in seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_downtime_seconds_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks history",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (increase(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "Total number of failed check {{ proxy }} / {{ server }}"
      },
      {
       "expr": "sum by (proxy, server) (increase(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$nodet\"}[5m]))",
       "legendFormat": "Total number of UP->DOWN transitions {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total of connection errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Current throttle percentage for the server, when slowstart is active, or no value if not in slowstart",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total number of times a service was selected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (haproxy_server_loadbalanced_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": " {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy, server) (irate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=~\"$node\"}[5m]))",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Service weight",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg by (proxy, server) (haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=~\"$node\"})",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - SSL cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_process_ssl_cache_lookups_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "Total number of SSL session cache lookups"
      },
      {
       "expr": "sum(irate(haproxy_process_ssl_cache_misses_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "Total number of SSL session cache misses"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(haproxy_process_current_frontend_ssl_key_rate{instance=~\"$node\"})",
       "legendFormat": "Current frontend SSL Key computation per second over last elapsed second"
      },
      {
       "expr": "sum(haproxy_process_current_backend_ssl_key_rate{instance=~\"$node\"})",
       "legendFormat": "Current backend SSL Key computation per second over last elapsed second"
      }
     ]
    },
    {
     "title": "Process - SSL rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(haproxy_process_current_ssl_rate{instance=~\"$node\"})",
       "legendFormat": "Current number of SSL sessions per second over last elapsed second"
      },
      {
       "expr": "sum(haproxy_process_limit_ssl_rate{instance=~\"$node\"})",
       "legendFormat": "Configured maximum number of SSL sessions per second"
      }
     ]
    },
    {
     "title": "Process - SSL connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(haproxy_process_current_ssl_connections{instance=~\"$node\"})",
       "legendFormat": "Current number of opened SSL connections"
      },
      {
       "expr": "sum(haproxy_process_max_ssl_connections{instance=~\"$node\"})",
       "legendFormat": "Configured maximum number of concurrent SSL connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(haproxy_process_frontent_ssl_reuse{instance=~\"$node\"})",
       "legendFormat": "SSL session reuse ratio (percent)"
      }
     ]
    }
   ]
  }
 ]
}