{
 "title": "GitLab Runners",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(gitlab_runner_jobs_total, pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Runner Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state)(gitlab_runner_autoscaling_machine_states{pool=~\"$pool\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(sum by (state)(gitlab_runner_autoscaling_machine_states{pool=~\"$pool\"}))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Runnings Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (gitlab_runner_jobs{pool=~\"$pool\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Runner Creation Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le)(increase(gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le)(increase(gitlab_runner_job_duration_seconds_bucket[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_failed_jobs_total{pool=~\"$pool\"})",
     "legendFormat": "Failed Jobs"
    }
   ]
  }
 ]
}