{
 "title": "Radius Logons",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Radius Connection Successes per Client (AP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (client_name) (count_over_time({job=\"winlog\", channel=\"Security\", app_mintel_com_job_label=~\"infra/.*-dc\"} |= \"Network Policy Server\" |= \"Audit Success\" != \"user because\" [1m]))",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Radius Connection Successes per DC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time({job=\"winlog\", channel=\"Security\", app_mintel_com_job_label=~\"infra/.*-dc\"} |= \"Network Policy Server\" |= \"Audit Success\" != \"user because\" [1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Radius Connection Failures per Client (AP)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (client_name) (count_over_time({job=\"winlog\", channel=\"Security\", app_mintel_com_job_label=~\"infra/.*-dc\"} |= \"Network Policy Server\" |= \"Audit failure\" [1m]))",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Invalid Radius Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (param1) (count_over_time({job=\"winlog\", channel=\"System\", app_mintel_com_job_label=~\"infra/.*-dc\"} |= \"NPS\" |= \"invalid RADIUS client\" [1m]))",
     "legendFormat": "{{param1}}"
    }
   ]
  },
  {
   "title": "Message Authenticator Invalid Attribute (bad secret?)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (param1) (count_over_time({job=\"winlog\", app_mintel_com_job_label=~\"infra/.*-dc\"} |= \"Message-Authenticator attribute that is not valid\" [1m]))",
     "legendFormat": "{{param1}}"
    }
   ]
  }
 ]
}