{
 "title": "Sentry.io",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(sentry_event_total, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Events by Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sentry_event_total{project=~\"$project\"}) by (stat_type)",
     "legendFormat": "{{stat_type}}"
    }
   ]
  },
  {
   "title": "Percentage of events rate limited",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sentry_event_total{stat_type=\"rejected\", project=~\"$project\"}) / sum(sentry_event_total{stat_type=\"received\", project=~\"$project\"})",
     "legendFormat": "Rejected"
    },
    {
     "expr": "avg_over_time((sum(sentry_event_total{stat_type=\"rejected\", project=~\"$project\"}) / (sum(sentry_event_total{stat_type=\"received\", project=~\"$project\"})))[24h:5m])",
     "legendFormat": "Daily Rolling Average"
    }
   ]
  },
  {
   "title": "Events Received per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project) (sentry_event_total{project=~\"$project\",stat_type=\"received\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Events Rejected per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project) (sentry_event_total{project=~\"$project\",stat_type=\"rejected\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Events Blacklisted per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project) (sentry_event_total{project=~\"$project\",stat_type=\"blacklisted\"})",
     "legendFormat": "{{project}}"
    }
   ]
  }
 ]
}