{
 "title": "Flux Daemon Metrics",
 "description": "Dashboard for Weave Flux",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(app_mintel_com_data_source)"
   },
   {
    "name": "service",
    "label": "Flux Service",
    "query": "label_values(flux_daemon_sync_duration_seconds_sum, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duration of git-to-cluster synchronisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(flux_daemon_sync_duration_seconds_sum{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_daemon_sync_duration_seconds_count{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (success) (rate(flux_daemon_sync_duration_seconds_sum{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_daemon_sync_duration_seconds_count{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Duration of remote image metadata requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(flux_client_fetch_duration_seconds_sum{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_client_fetch_duration_seconds_count{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (success) (rate(flux_client_fetch_duration_seconds_sum{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_client_fetch_duration_seconds_count{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Duration of cache requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(flux_cache_request_duration_seconds_sum{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_cache_request_duration_seconds_count{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (success) (rate(flux_cache_request_duration_seconds_sum{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_cache_request_duration_seconds_count{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Duration of time spent in the job queue before execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flux_daemon_queue_duration_seconds_sum{service=\"$service\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_daemon_queue_duration_seconds_count{service=\"$service\",app_mintel_com_data_source=\"$cluster\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Duration of job execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(flux_daemon_job_duration_seconds_sum{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_daemon_job_duration_seconds_count{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (success) (rate(flux_daemon_job_duration_seconds_sum{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_daemon_job_duration_seconds_count{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Duration of the current connection to fluxsvc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flux_fluxd_connection_duration_seconds{service=\"$service\",app_mintel_com_data_source=\"$cluster\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Count of jobs waiting in the queue to be run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flux_daemon_queue_length_count{service=\"$service\",app_mintel_com_data_source=\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Duration of image metadata requests (from cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(flux_registry_fetch_duration_seconds_sum{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_registry_fetch_duration_seconds_count{service=\"$service\", success=\"true\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (success) (rate(flux_registry_fetch_duration_seconds_sum{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]) / rate(flux_registry_fetch_duration_seconds_count{service=\"$service\", success=\"false\",app_mintel_com_data_source=\"$cluster\"}[$__interval]))",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}